In [1]:
# importing Numpy package
import numpy as np
# creating a 3X3 Numpy matrix
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
# calculating the determinant of matrix
det = np.linalg.det(n_array)
print("\nDeterminant of given 3X3 square matrix:")
print(int(det))

print("inv matrix")
print(np.linalg.inv(n_array))

print("multy matrix")
print(n_array@n_array)


Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Determinant of given 3X3 square matrix:
137180
inv matrix
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
multy matrix
[[3940 3150 2030]
 [2992 2776  692]
 [2802 5720 6184]]
